codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 1
    wait_for_ci: false

coverage:
  precision: 2
  round: down
  range: "30...100"

  status:
    project:
      default:
        target: auto
        threshold: 10%
        base: auto
        if_not_found: success
        if_ci_failed: success
        informational: true
    patch:
      default:
        target: 0%
        threshold: 100%
        base: auto
        if_not_found: success
        if_ci_failed: success
        only_pulls: true
        informational: true
    changes: false

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "tests/**/*"
  - "**/*_test.rs"
  - "**/*.test.rs"
  - "**/tests/**"
  - "**/target/**"