services:
  groups_relay:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - DEBIAN_FRONTEND=noninteractive
    environment:
      NIP29__relay__auth_url: "ws://localhost:8080"