# Local development relay configuration
relay:
  db_path: "./db"
  relay_url: "ws://localhost:8080"

  # WebSocket settings for testing limits
  websocket:
    # Small channel size to test backpressure
    channel_size: 1000
    # Short connection time to test auto-disconnect
    max_connection_time: "5m"
    # Small number of connections to test connection limiting
    max_connections: 300
