# Local development relay configuration
relay:
  auth_url: "ws://0.0.0.0:8080"
  db_path: "./db"

  # WebSocket settings for testing limits
  websocket:
    # Small channel size to test backpressure
    channel_size: 1000
    # Short connection time to test auto-disconnect
    max_connection_time: "5s"
    # Small number of connections to test connection limiting
    max_connections: 300
