name: Build and Push Profile Aggregator Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'crates/profile_aggregator/**'
      - 'crates/nostr_relay_builder/**'
      - 'crates/nostr/**'
      - 'crates/scoped-heed/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/profile-aggregator-docker.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'crates/profile_aggregator/**'
      - 'crates/nostr_relay_builder/**'
      - 'crates/nostr/**'
      - 'crates/scoped-heed/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/profile-aggregator-docker.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: verse-pbc/profile_aggregator

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./crates/profile_aggregator/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64